version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - passauth-express-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: passauth_express

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - passauth-express-redis-data:/data

volumes:
  passauth-express-db:
  passauth-express-redis-data:
